apiVersion: v1
kind: PersistentVolume
metadata:
  name: csv-exports-pv
  namespace: shipment-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /Users/bkhafizull/IdeaProjects/msa-project-5/task-3/results/csv
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-exports-pvc
  namespace: shipment-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: csv-exports-pv
